spring:
  jpa:
    # 전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    # 테이블 생성 후에 data.sql 실행
    defer-datasource-initialization: true

  #  datasource:
  #    url: jdbc:h2:mem:testdb
  #    username: sa

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 690154209830-rg21o4rvgi91vels18rlfrpo0mk1831i.apps.googleusercontent.com
            client-secret: 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
          scope:
            - email
            - profile
  
  h2:
    console:
      enabled: true

jwt:
  issuer: dustjq1005@naver.com
  secret_key: study_springboot