spring:
  config:
    activate:
      on-profile: test
    import: optional:file:.env[.properties]

  lifecycle:
    timeout-per-shutdown-phase: 30s
  jpa:
    # 전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

    # 테이블 생성 후에 data.sql 실행
    defer-datasource-initialization: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    user: sa

  h2:
    console:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: client-id
            client-secret: client-secret
            scope:
              - email
              - profile


server:
  shutdown: graceful

jwt:
  issuer: dustjq1005@gmail.com
  secret_key: secret-key

cloud:
  aws:
    region: ap-northeast-2
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
  s3:
    bucket: suplab-bucket

logging:
  level:
    org:
      hibernate:
        SQL: debug #
        orm:
          jdbc:
            bind: trace
