spring:
  config:
    activate:
      on-profile: test

  lifecycle:
    timeout-per-shutdown-phase: 30s
  jpa:
    # 전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    # 테이블 생성 후에 data.sql 실행
    defer-datasource-initialization: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    user: sa

  h2:
    console:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: client-id
            client-secret: client-secret
            scope:
              - email
              - profile

  devtools:
    livereload:
      enabled: true
    thymeleaf:
      cache: false
    restart:
      enabled: true


server:
  shutdown: graceful
  servlet:
    session:
      # 어플리케이션 재 build시 세션 유지 여부 설정
      persistent: false

jwt:
  issuer: dustjq1005@gmail.com
  secret_key: secret-key

cloud:
  aws:
    region: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true
  s3:
    bucket: elasticbeanstalk-ap-northeast-2-205011928457

