spring:
  config:
    activate:
      on-profile: dev
  lifecycle:
    timeout-per-shutdown-phase: 30s
  datasource:
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}
    driver-class-name: ${rds.driver}
    username: ${rds.username}
    password: ${rds.password}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: client-id
            client-secret: client-secret
            scope:
              - email
              - profile

server:
  shutdown: graceful
  forward-headers-strategy: native

jwt:
  issuer: dustjq1005@gmail.com
  secret_key: secret-key

cloud:
  aws:
    region: ap-northeast-2
    stack:
      auto: false
    credentials:
      instance-profile: true
  s3:
    bucket: suplab-bucket
