spring:
  config:
    activate:
      on-profile: dev
  lifecycle:
    timeout-per-shutdown-phase: 30s

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: client-id
            client-secret: client-secret
            scope:
              - email
              - profile
server:
  shutdown: graceful

jwt:
  issuer: dustjq1005@gmail.com
  secret_key: secret-key

cloud:
  aws:
    region: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true
  s3:
    bucket: elasticbeanstalk-ap-northeast-2-205011928457
